"""Initial schema

Revision ID: 326e85a8fea9
Revises:
Create Date: 2026-09-14 00:27:58.809071

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "326e85a8fea9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
